---
- name: Install Dependencies
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - make
  become: true

- name: Download Redis
  when: not offline
  get_url:
    url: "{{ redis_download_url }}"
    dest: "{{ download_dir }}/redis-{{ redis_version }}.tar.gz"
  become: true
  become_user: ozp

- name: upload redis
  when: offline
  copy:
    src: "{{ redis_tarball }}"
    dest: /usr/local/src/redis-{{ redis_version }}.tar.gz
  when: redis_tarball

- name: Extract Redis tarball
  unarchive:
    src: /usr/local/src/redis-{{ redis_version }}.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/redis-{{ redis_version }}/Makefile
    copy: no

- name: Compile Redis
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: /usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: Create redis install directory
  file:
    path: "{{ redis_install_dir }}"
    state: directory

- name: Create /etc/redis
  file:
    path: /etc/redis
    state: directory

- name: Create redis user
  user:
    name: "{{ redis_user }}"
    comment: "redis"
    home: "{{ redis_install_dir }}"
    shell: /bin/false
    system: yes
  become: true

- name: Create /var/run/redis
  file:
    path: /var/run/redis
    state: directory
    owner: "{{ redis_user }}"

- name: Install redis
  command: make PREFIX={{ redis_install_dir }} install
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    creates: "{{ redis_install_dir }}/bin/redis-server"
