---
- hosts: buildservers
  roles:
    #- common
    - no_internet
    #- ssl_certs
    #- nginx
    #- python_3
    #- node
    #- postgres
    #- ozp_authorization
    #- ozp_backend
    #- ozp_center
    #- ozp_config
