---
- hosts: buildservers
  roles:
    #- common
    - offline
    #- ssl_certs
    #- nginx
    #- python_3
    #- node
    #- postgres
    #- ozp_authorization
    - ozp_backend
    #- ozp_center
    #- ozp_hud
    #- ozp_webtop
    #- ozp_iwc
    #- ozp_demo_apps
    #- ozp_config
