---
- hosts: hosts_ci
  remote_user: root

  tasks:
  - name: download python source
    get_url:  url=https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version}}.tgz
      dest={{ download_dir }} mode=0644

  - name: build and install python
    command: tar -xzf Python-{{ python_version }}.tgz
      args:
        chdir={{ download_dir }}

    command: ./configure --prefix=/usr/local --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
      args:
        chdir={{ download_dir/Python-{{ python_version }}}}

    command: make
      args:
        chdir={{ download_dir/Python-{{ python_version }}}}

    command: sudo make altinstall
      args:
        chdir={{ download_dir/Python-{{ python_version }}}}
