---
# valid choices are "jenkins", "github", or "local"
download_from: "github"
 # branch or tag name to checkout from git repo
git_tag_or_branch_name: "master"
# if jenkins, choose a project name and build number
jenkins_project: "build-demo-latest"
jenkins_build_number: 51
# for ozpIwc.conf.js
api_root_url: "/api"
# for OzoneConfig.js
iwc_url: "https://{{ server_fqdn }}:{{ server_port }}/iwc"
node_version: 0.12.7
