---
- name: Install prereqs
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - vim
    - git
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel
    - libjpeg-devel
    - libselinux-python # required for ansible i guess

  become: true

- name: Install httplib2 (or other things from the epel)
  yum: name={{ item }} state=present
  with_items:
    - python-httplib2 # required to use uri module in ansible
  become: true

- name: Install development tools
  yum: name='@development'
  become: true

- name: Create ozp user
  user:
    name: ozp
    comment: "ozp"
    # group: ozp
    password: "password"
  become: true

- name: Create /usr/local/ozp directory
  file:
    path: /usr/local/ozp
    owner: ozp
    mode: 0755
    recurse: true
    state: directory
  become: true
