---
- name: Install prereqs
  yum: name={{ items }} state=present
  with_items:
    - epel-release
    - vim
    - git
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel

- name: Install development tools
  yum: name='@development'
