---
- name: Install postgres dependencies
  yum: name={{ item }} state=present
  with_items:
    - readline-devel
    - libtermcap-devel
  become: true

- name: Download postgres
  get_url:
    url: https://ftp.postgresql.org/pub/source/v{{ postgres_version }}/postgresql-{{ postgres_version }}.tar.gz
    dest: "{{ download_dir }}/postgresql-{{ postgres_version }}.tar.gz"

- name: Extract archive
  unarchive:
    src: "{{ download_dir }}/postgresql-{{ postgres_version }}.tar.gz"
    dest: "{{ download_dir }}"
    copy: no

- name: Configure postgres
  command: ./configure
  args:
    chdir: "{{ download_dir }}/postgresql-{{ postgres_version }}"

- name: Build postgres
  command: make
  args:
    chdir: "{{ download_dir }}/postgresql-{{ postgres_version }}"

- name: Install postgres
  command: make install
  args:
    chdir: "{{ download_dir }}/postgresql-{{ postgres_version }}"
  become: true
